# -*- coding: utf-8 -*-
"""Meta2_1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14GsJ62dUfXbwf--bS43nm6uvH9iFmEOH
"""

# demo02_linearRegression.py
import numpy as np
import matplotlib.pyplot as plt


# Carga el dataset
data = np.loadtxt('slump_test.dat',delimiter=',')
x = data[:,1:8]
y = data[:,8:12]
# Genera la matriz de diseno
q,_ = np.shape(x)
_,m = np.shape(y)

A = np.c_[x,np.ones((q,1))]
# Optimizacion
ATA = A.T @ A
b = A.T @ y
theta = np.linalg.pinv(ATA) @ b
# Evalua la hipotesis
yh = A @ theta
# Evalua metricas
e = y-yh
ev = e.flatten(order='F')
SSE = ev.T @ ev
MSE = SSE/(q*m)
RMSE = np.math.sqrt(MSE)
# Evalua coeficiente de determinación (𝑅2)
yb = np.mean(y)
e = y-yb
ev = e.flatten(order = 'F')
SST = ev.T @ ev
R2 = 1-SSE/SST

print("SSE   = ",SSE)
print("MSE   = ",MSE)
print("RMSE  = ",RMSE)
print("R2    = ",R2)
print("\nTHETA = ",theta)